#USERS
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Debora
spec:
  displayName: Debora Gama
  email: debora.gama@instruct.com.br
  memberOf: [school-devops, Instruct]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Ana
spec:
  displayName: Ana Cândida
  email: ana.candida@instruct.com
  memberOf: [school-devops, Instruct]
---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: school-devops
spec:
  type: team
  children: []
  # parent: [Instruct]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Instruct
spec:
  type: group
  children: [school-devops]
